import type { Metadata } from "next";
import { AR_One_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/lib/auth/auth";
import { headers } from "next/headers";
import NextTopLoader from "nextjs-toploader";

import TRPCAppProvider from "@/providers/TRPCProvider";
import DotGrid from "@/components/features/DotGrid";
const arOneSans = AR_One_Sans({
  weight: ["400", "500", "600", "700"],
  variable: "--font-arOneSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${arOneSans.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader
            color="#f4ac96de"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            showSpinner={false}
            crawl={true}
            easing="ease"
            speed={200}
            shadow="0 0 10px #f4ac96de,0 0 5px #f4ac96de"
            template='<div class="bar" role="bar"><div class="peg"></div></div> 
  <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
            zIndex={1600}
            showAtBottom={false}
          />

          <TRPCAppProvider>
            <Navbar user={session?.user} />
            <main className="w-full min-h-screen relative pb-20">
              <DotGrid
                dotSize={2}
                gap={15}
                baseColor="#e05d38"
                activeColor="#e05d38"
                proximity={100}
                shockRadius={50}
                shockStrength={50}
                resistance={750}
                returnDuration={1.5}
                style={{
                  position: "absolute",
                  opacity: 0.3,
                  zIndex: -1,
                }}
              />
              {children}
            </main>
          </TRPCAppProvider>
          <Toaster
            richColors
            position="bottom-center"
            closeButton
            visibleToasts={2}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
